-- InitializeDatabase.sql
-- SQL script to create the tables in the database

-- Create table 'Questions'
CREATE TABLE "Questions"
(
    "QuestionId"       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AcceptedAnswerId" BIGINT,
    "AnswerCount"      INTEGER      NOT NULL,
    "ClosedDate"       BIGINT,
    "CreationDate"     BIGINT       NOT NULL,
    "IsAnswered"       BOOLEAN,
    "LastActivityDate" BIGINT       NOT NULL,
    "LastEditDate"     BIGINT       NOT NULL,
    "Link"             VARCHAR(510) NOT NULL,
    "Score"            INTEGER      NOT NULL,
    "Title"            VARCHAR(510) NOT NULL,
    "ViewCount"        INTEGER      NOT NULL
);

-- Create table 'QuestionTags'
CREATE TABLE "QuestionTags"
(
    "QuestionId" BIGINT       NOT NULL,
    "Tag"        VARCHAR(255) NOT NULL,
    PRIMARY KEY ("QuestionId", "Tag"),
    CONSTRAINT "FK_QuestionTags_Questions_QuestionId"
        FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("QuestionId")
            ON DELETE CASCADE
);
