spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stackexchangedb
    # this command allows you to see the size of the database
    # SELECT pg_size_pretty(pg_database_size('stackexchangedb')) AS size;
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    database: postgresql
    database-platform: PostgreSQLDialect

  cache:
    type: redis

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:8888}
    time-to-live: 60 # the time to live in seconds

stack-exchange:
  api-key: Ve4rjNkrFc*ZJqf25pA2ZA((
  base-url: https://api.stackexchange.com/2.2
  programming-languages:
    - java
    - python
    - javascript
    - go
    - kotlin
    - swift
    - php
    - ruby
    - c++
    - c#